#!/bin/bash
#This script is for a specific architecture make changes based on the counters available on your machine.
FILENAME="Matrix_Mult"

#UBOX0 = 4 values
UBOX0=("TRK_OCCUPANCY_ALL" "COH_TRK_OCCUPANCY")
#UBOX1 = 4 values
UBOX1=("TRK_REQUESTS_ALL" "TRK_REQUESTS_WRITES" "COH_TRK_REQUESTS_ALL")
#PMC = 4 values
PMC=("ICACHE_16B_IFDATA_STALL" "ICACHE_64B_IFTAG_HIT" "ICACHE_64B_IFTAG_MISS" "ICACHE_64B_IFTAG_ALL" "ICACHE_64B_IFTAG_STALL" "CPU_CLOCK_UNHALTED_THREAD_P" "CPU_CLOCK_UNHALTED_THREAD_P_ANY" "CPU_CLOCK_UNHALTED_REF_XCLK" "CPU_CLOCK_UNHALTED_REF_XCLK_ANY" "CPU_CLOCK_UNHALTED_ONE_THREAD_ACTIVE" "CPU_CLOCK_UNHALTED_TOTAL_CYCLES" "BACLEARS_ANY" "ITLB_FLUSH" "ILD_STALL_LCP" "IDQ_UOPS_NOT_DELIVERED_CORE" "IDQ_UOPS_NOT_DELIVERED_CYCLES_0_UOPS_DELIV_CORE" "IDQ_UOPS_NOT_DELIVERED_CYCLES_LE_1_UOP_DELIV_CORE" "IDQ_UOPS_NOT_DELIVERED_CYCLES_LE_2_UOP_DELIV_CORE" "IDQ_UOPS_NOT_DELIVERED_CYCLES_LE_3_UOP_DELIV_CORE" "IDQ_UOPS_NOT_DELIVERED_CYCLES_FE_WAS_OK" "DSB2MITE_SWITCHES_PENALTY_CYCLES" "INT_MISC_RECOVERY_CYCLES" "INT_MISC_RECOVERY_COUNT" "INT_MISC_RECOVERY_CYCLES_ANY" "INT_MISC_RECOVERY_COUNT_ANY" "INT_MISC_CLEAR_RESTEER_CYCLES" "INT_MISC_CLEAR_RESTEER_COUNT" "RESOURCE_STALLS_ANY" "RESOURCE_STALLS_SB" "PARTIAL_RAT_STALLS_SCOREBOARD" "UOPS_ISSUED_ANY" "UOPS_ISSUED_VECTOR_WIDTH_MISMATCH" "UOPS_ISSUED_SLOW_LEA" "UOPS_ISSUED_USED_CYCLES" "UOPS_ISSUED_STALL_CYCLES" "UOPS_ISSUED_TOTAL_CYCLES" "UOPS_ISSUED_CORE_USED_CYCLES" "UOPS_ISSUED_CORE_STALL_CYCLES" "UOPS_ISSUED_CORE_TOTAL_CYCLES" "UOPS_ISSUED_CYCLES_GE_1_UOPS_EXEC" "UOPS_ISSUED_CYCLES_GE_2_UOPS_EXEC" "UOPS_ISSUED_CYCLES_GE_3_UOPS_EXEC" "UOPS_ISSUED_CYCLES_GE_4_UOPS_EXEC" "UOPS_ISSUED_CYCLES_GE_5_UOPS_EXEC" "TX_EXEC_MISC1" "TX_EXEC_MISC2" "TX_EXEC_MISC3" "TX_EXEC_MISC4" "TX_EXEC_MISC5" "RS_EVENTS_EMPTY_CYCLES" "RS_EVENTS_EMPTY_END" "HLE_RETIRED_START" "HLE_RETIRED_COMMIT" "HLE_RETIRED_ABORTED" "HLE_RETIRED_ABORTED_MEM" "HLE_RETIRED_ABORTED_TIMER" "HLE_RETIRED_ABORTED_UNFRIENDLY" "HLE_RETIRED_ABORTED_MEMTYPE" "HLE_RETIRED_ABORTED_EVENTS" "RTM_RETIRED_START" "RTM_RETIRED_COMMIT" "RTM_RETIRED_ABORTED" "RTM_RETIRED_ABORTED_MEM" "RTM_RETIRED_ABORTED_TIMER" "RTM_RETIRED_ABORTED_UNFRIENDLY" "RTM_RETIRED_ABORTED_MEMTYPE" "RTM_RETIRED_ABORTED_EVENTS" "MACHINE_CLEARS_COUNT" "MACHINE_CLEARS_MEMORY_ORDERING" "MACHINE_CLEARS_SMC" "HW_INTERRUPTS_RECEIVED" "INST_RETIRED_ANY" "UOPS_RETIRED_ALL" "UOPS_RETIRED_CORE_ALL" "UOPS_RETIRED_RETIRE_SLOTS" "UOPS_RETIRED_USED_CYCLES" "UOPS_RETIRED_STALL_CYCLES" "UOPS_RETIRED_TOTAL_CYCLES" "UOPS_RETIRED_CORE_RETIRE_SLOTS" "UOPS_RETIRED_CORE_USED_CYCLES" "UOPS_RETIRED_CORE_STALL_CYCLES" "UOPS_RETIRED_CORE_TOTAL_CYCLES" "UOPS_RETIRED_CYCLES_GE_1_UOPS_EXEC" "UOPS_RETIRED_CYCLES_GE_2_UOPS_EXEC" "UOPS_RETIRED_CYCLES_GE_3_UOPS_EXEC" "UOPS_RETIRED_CYCLES_GE_4_UOPS_EXEC" "UOPS_RETIRED_CYCLES_GE_5_UOPS_EXEC" "UOPS_RETIRED_CYCLES_GE_6_UOPS_EXEC" "UOPS_RETIRED_CYCLES_GE_7_UOPS_EXEC" "UOPS_RETIRED_CYCLES_GE_8_UOPS_EXEC" "BR_INST_RETIRED_ALL_BRANCHES" "BR_INST_RETIRED_CONDITIONAL" "BR_INST_RETIRED_NEAR_CALL" "BR_INST_RETIRED_NEAR_RETURN" "BR_INST_RETIRED_NOT_TAKEN" "BR_INST_RETIRED_NEAR_TAKEN" "BR_INST_RETIRED_FAR_BRANCH" "BR_MISP_RETIRED_ALL_BRANCHES" "BR_MISP_RETIRED_CONDITIONAL" "BR_MISP_RETIRED_NEAR_TAKEN" "FP_ARITH_INST_RETIRED_SCALAR_DOUBLE" "FP_ARITH_INST_RETIRED_SCALAR_SINGLE" "FP_ARITH_INST_RETIRED_128B_PACKED_DOUBLE" "FP_ARITH_INST_RETIRED_128B_PACKED_SINGLE" "FP_ARITH_INST_RETIRED_256B_PACKED_DOUBLE" "FP_ARITH_INST_RETIRED_256B_PACKED_SINGLE" "FP_ASSIST_ANY" "MEM_INST_RETIRED_STLB_MISS_LOADS" "MEM_INST_RETIRED_STLB_MISS_STORES" "MEM_INST_RETIRED_LOCK_LOADS" "MEM_INST_RETIRED_SPLIT_LOADS" "MEM_INST_RETIRED_SPLIT_STORES" "MEM_INST_RETIRED_ALL_LOADS" "MEM_INST_RETIRED_ALL_STORES" "MEM_INST_RETIRED_ALL" "MEM_LOAD_RETIRED_L1_HIT" "MEM_LOAD_RETIRED_L2_HIT" "MEM_LOAD_RETIRED_L3_HIT" "MEM_LOAD_RETIRED_L1_MISS" "MEM_LOAD_RETIRED_L2_MISS" "MEM_LOAD_RETIRED_L3_MISS" "MEM_LOAD_RETIRED_FB_HIT" "MEM_LOAD_RETIRED_L1_ALL" "MEM_LOAD_RETIRED_L2_ALL" "MEM_LOAD_RETIRED_L3_ALL" "MEM_LOAD_L3_HIT_RETIRED_XSNP_MISS" "MEM_LOAD_L3_HIT_RETIRED_XSNP_HIT" "MEM_LOAD_L3_HIT_RETIRED_XSNP_HITM" "MEM_LOAD_L3_HIT_RETIRED_XSNP_NONE" "FRONTEND_RETIRED_DSB_MISS" "FRONTEND_RETIRED_L1I_MISS" "FRONTEND_RETIRED_L2_MISS" "FRONTEND_RETIRED_ITLB_MISS" "FRONTEND_RETIRED_STLB_MISS" "FRONTEND_RETIRED_LATENCY_GE_2" "FRONTEND_RETIRED_LATENCY_GE_2_BUBBLES_GE_2" "FRONTEND_RETIRED_LATENCY_GE_4" "UOPS_EXECUTED_THREAD" "UOPS_EXECUTED_USED_CYCLES" "UOPS_EXECUTED_STALL_CYCLES" "UOPS_EXECUTED_TOTAL_CYCLES" "UOPS_EXECUTED_CYCLES_GE_1_UOPS_EXEC" "UOPS_EXECUTED_CYCLES_GE_2_UOPS_EXEC" "UOPS_EXECUTED_CYCLES_GE_3_UOPS_EXEC" "UOPS_EXECUTED_CYCLES_GE_4_UOPS_EXEC" "UOPS_EXECUTED_CYCLES_GE_5_UOPS_EXEC" "UOPS_EXECUTED_CYCLES_GE_6_UOPS_EXEC" "UOPS_EXECUTED_CYCLES_GE_7_UOPS_EXEC" "UOPS_EXECUTED_CYCLES_GE_8_UOPS_EXEC" "UOPS_EXECUTED_CORE" "UOPS_EXECUTED_CORE_USED_CYCLES" "UOPS_EXECUTED_CORE_STALL_CYCLES" "UOPS_EXECUTED_CORE_TOTAL_CYCLES" "UOPS_EXECUTED_CORE_CYCLES_GE_1_UOPS_EXEC" "UOPS_EXECUTED_CORE_CYCLES_GE_2_UOPS_EXEC" "UOPS_EXECUTED_CORE_CYCLES_GE_3_UOPS_EXEC" "UOPS_EXECUTED_CORE_CYCLES_GE_4_UOPS_EXEC" "UOPS_EXECUTED_CORE_CYCLES_GE_5_UOPS_EXEC" "UOPS_EXECUTED_CORE_CYCLES_GE_6_UOPS_EXEC" "UOPS_EXECUTED_CORE_CYCLES_GE_7_UOPS_EXEC" "UOPS_EXECUTED_CORE_CYCLES_GE_8_UOPS_EXEC" "UOPS_EXECUTED_X87" "EXE_ACTIVITY_EXE_BOUND_0_PORTS" "EXE_ACTIVITY_1_PORTS_UTIL" "EXE_ACTIVITY_2_PORTS_UTIL" "EXE_ACTIVITY_3_PORTS_UTIL" "EXE_ACTIVITY_4_PORTS_UTIL" "EXE_ACTIVITY_BOUND_ON_STORES" "UOPS_DISPATCHED_PORT_PORT_0" "UOPS_DISPATCHED_PORT_PORT_1" "UOPS_DISPATCHED_PORT_PORT_2" "UOPS_DISPATCHED_PORT_PORT_3" "UOPS_DISPATCHED_PORT_PORT_4" "UOPS_DISPATCHED_PORT_PORT_5" "UOPS_DISPATCHED_PORT_PORT_6" "UOPS_DISPATCHED_PORT_PORT_7" "UOPS_DISPATCHED_PORT_ARITH_PORTS" "UOPS_DISPATCHED_PORT_ARITH_PORTS_CORE" "UOPS_DISPATCHED_PORT_DATA_PORTS" "CYCLE_ACTIVITY_STALLS_TOTAL" "CYCLE_ACTIVITY_CYCLES_NO_EXECUTE" "CYCLE_ACTIVITY_CYCLES_L2_MISS" "CYCLE_ACTIVITY_STALLS_L2_MISS" "CYCLE_ACTIVITY_CYCLES_L2_PENDING" "CYCLE_ACTIVITY_STALLS_L2_PENDING" "CYCLE_ACTIVITY_CYCLES_L3_MISS" "CYCLE_ACTIVITY_STALLS_L3_MISS" "CYCLE_ACTIVITY_CYCLES_L3_PENDING" "CYCLE_ACTIVITY_STALLS_L3_PENDING" "CYCLE_ACTIVITY_CYCLES_MEM_ANY" "CYCLE_ACTIVITY_STALLS_MEM_ANY" "CYCLE_ACTIVITY_CYCLES_LDM_PENDING" "CYCLE_ACTIVITY_STALLS_LDM_PENDING" "CYCLE_ACTIVITY_CYCLES_L1D_MISS" "CYCLE_ACTIVITY_STALLS_L1D_MISS" "CYCLE_ACTIVITY_CYCLES_L1D_PENDING" "CYCLE_ACTIVITY_STALLS_L1D_PENDING" "EPT_WALK_PENDING" "ITLB_MISSES_CAUSES_A_WALK" "ITLB_MISSES_WALK_PENDING" "ITLB_MISSES_STLB_HIT" "ITLB_MISSES_WALK_COMPLETED" "ITLB_MISSES_WALK_COMPLETED_4K" "ITLB_MISSES_WALK_COMPLETED_2M_4M" "ITLB_MISSES_WALK_COMPLETED_1G" "ITLB_MISSES_WALK_ACTIVE" "DTLB_LOAD_MISSES_CAUSES_A_WALK" "DTLB_LOAD_MISSES_WALK_PENDING" "DTLB_LOAD_MISSES_STLB_HIT" "DTLB_LOAD_MISSES_WALK_COMPLETED" "DTLB_LOAD_MISSES_WALK_COMPLETED_4K" "DTLB_LOAD_MISSES_WALK_COMPLETED_2M_4M" "DTLB_LOAD_MISSES_WALK_COMPLETED_1G" "DTLB_LOAD_MISSES_WALK_ACTIVE" "DTLB_STORE_MISSES_CAUSES_A_WALK" "DTLB_STORE_MISSES_WALK_PENDING" "DTLB_STORE_MISSES_STLB_HIT" "DTLB_STORE_MISSES_WALK_COMPLETED" "DTLB_STORE_MISSES_WALK_COMPLETED_4K" "DTLB_STORE_MISSES_WALK_COMPLETED_2M_4M" "DTLB_STORE_MISSES_WALK_COMPLETED_1G" "DTLB_STORE_MISSES_WALK_ACTIVE" "TLB_FLUSH_DTLB_THREAD" "TLB_FLUSH_STLB_ANY" "L1D_REPLACEMENT" "L1D_M_EVICT" "TX_MEM_ABORT_CONFLICT" "TX_MEM_ABORT_CAPACITY" "TX_MEM_ABORT_HLE_STORE_TO_ELIDED_LOCK" "TX_MEM_ABORT_HLE_ELISION_BUFFER_NOT_EMPTY" "TX_MEM_ABORT_HLE_ELISION_BUFFER_MISMATCH" "TX_MEM_ABORT_HLE_ELISION_BUFFER_UNSUPPORTED_ALIGNMENT" "TX_MEM_HLE_ELISION_BUFFER_FULL" "L1D_PEND_MISS_PENDING" "L1D_PEND_MISS_FB_FULL" "L1D_PEND_MISS_PENDING_CYCLES" "L1D_PEND_MISS_PENDING_CYCLES_ANY" "LOAD_HIT_PRE_SW_PF" "LOCK_CYCLES_CACHE_LOCK_DURATION" "LOCK_CYCLES_CACHE_LOCK_COUNT" "LD_BLOCKS_STORE_FORWARD" "LD_BLOCKS_NO_SR" "LD_BLOCKS_PARTIAL_ADDRESS_ALIAS" "OFFCORE_REQUESTS_DEMAND_DATA_RD" "OFFCORE_REQUESTS_DEMAND_CODE_RD" "OFFCORE_REQUESTS_DEMAND_RFO" "OFFCORE_REQUESTS_ALL_DATA_RD" "OFFCORE_REQUESTS_L3_MISS_DEMAND_DATA_RD" "OFFCORE_REQUESTS_ALL_REQUESTS" "OFFCORE_REQUESTS_OUTSTANDING_DEMAND_DATA_RD" "OFFCORE_REQUESTS_OUTSTANDING_DEMAND_DATA_RD_GE_6" "OFFCORE_REQUESTS_OUTSTANDING_DEMAND_CODE_RD" "OFFCORE_REQUESTS_OUTSTANDING_DEMAND_RFO" "OFFCORE_REQUESTS_OUTSTANDING_ALL_DATA_RD" "OFFCORE_REQUESTS_OUTSTANDING_L3_MISS_DEMAND_DATA_RD" "OFFCORE_REQUESTS_OUTSTANDING_CYCLES_WITH_DEMAND_DATA_RD" "OFFCORE_REQUESTS_OUTSTANDING_CYCLES_WITH_DATA_RD" "OFFCORE_REQUESTS_OUTSTANDING_CYCLES_WITH_DEMAND_CODE_RD" "OFFCORE_REQUESTS_OUTSTANDING_CYCLES_WITH_DEMAND_RFO" "OFFCORE_REQUESTS_OUTSTANDING_CYCLES_WITH_L3_MISS_DEMAND_DATA_RD" "OFFCORE_REQUESTS_OUTSTANDING_L3_MISS_DEMAND_DATA_RD_GE_6" "OFFCORE_REQUESTS_BUFFER_SQ_FULL" "L2_TRANS_DEMAND_DATA_RD" "L2_TRANS_RFO" "L2_TRANS_CODE_RD" "L2_TRANS_ALL_PF" "L2_TRANS_L1D_WB" "L2_TRANS_L2_FILL" "L2_TRANS_L2_WB" "L2_TRANS_ALL_REQUESTS" "LONGEST_LAT_CACHE_MISS" "LONGEST_LAT_CACHE_REFERENCE" "L2_RQSTS_DEMAND_DATA_RD_MISS" "L2_RQSTS_DEMAND_DATA_RD_HIT" "L2_RQSTS_ALL_DEMAND_DATA_RD" "L2_RQSTS_ALL_RFO" "L2_RQSTS_ALL_CODE_RD" "L2_RQSTS_ALL_PF" "L2_RQSTS_PF_MISS" "L2_RQSTS_PF_HIT" "L2_RQSTS_RFO_HIT" "L2_RQSTS_RFO_MISS" "L2_RQSTS_CODE_RD_HIT" "L2_RQSTS_CODE_RD_MISS" "L2_RQSTS_ALL_DEMAND_MISS" "L2_RQSTS_ALL_DEMAND_REFERENCES" "L2_RQSTS_MISS" "L2_RQSTS_REFERENCES" "IDQ_MITE_UOPS" "IDQ_DSB_UOPS" "IDQ_MS_DSB_UOPS" "IDQ_MS_MITE_UOPS" "IDQ_MS_UOPS" "IDQ_MITE_CYCLES" "IDQ_MITE_CYCLES_1_UOPS" "IDQ_MITE_CYCLES_2_UOPS" "IDQ_MITE_CYCLES_3_UOPS" "IDQ_MITE_CYCLES_4_UOPS" "IDQ_MITE_CYCLES_5_UOPS" "IDQ_MITE_CYCLES_6_UOPS" "IDQ_DSB_CYCLES" "IDQ_DSB_CYCLES_1_UOPS" "IDQ_DSB_CYCLES_2_UOPS" "IDQ_DSB_CYCLES_3_UOPS" "IDQ_DSB_CYCLES_4_UOPS" "IDQ_DSB_CYCLES_5_UOPS" "IDQ_DSB_CYCLES_6_UOPS" "IDQ_MS_DSB_CYCLES" "IDQ_MS_DSB_CYCLES_1_UOPS" "IDQ_MS_DSB_CYCLES_2_UOPS" "IDQ_MS_DSB_CYCLES_3_UOPS" "IDQ_MS_DSB_CYCLES_4_UOPS" "IDQ_MS_DSB_CYCLES_5_UOPS" "IDQ_MS_DSB_CYCLES_6_UOPS" "IDQ_MS_DSB_OCCUR" "IDQ_MS_MITE_CYCLES" "IDQ_MS_MITE_CYCLES_1_UOPS" "IDQ_MS_MITE_CYCLES_2_UOPS" "IDQ_MS_MITE_CYCLES_3_UOPS" "IDQ_MS_MITE_CYCLES_4_UOPS" "IDQ_MS_MITE_CYCLES_5_UOPS" "IDQ_MS_MITE_CYCLES_6_UOPS" "IDQ_MS_CYCLES" "IDQ_MS_CYCLES_1_UOPS" "IDQ_MS_CYCLES_2_UOPS" "IDQ_MS_CYCLES_3_UOPS" "IDQ_MS_CYCLES_4_UOPS" "IDQ_MS_CYCLES_5_UOPS" "IDQ_MS_CYCLES_6_UOPS" "IDQ_MS_SWITCHES" "IDQ_ALL_DSB_CYCLES_ANY_UOPS" "IDQ_ALL_DSB_CYCLES_1_UOPS" "IDQ_ALL_DSB_CYCLES_2_UOPS" "IDQ_ALL_DSB_CYCLES_3_UOPS" "IDQ_ALL_DSB_CYCLES_4_UOPS" "IDQ_ALL_DSB_CYCLES_5_UOPS" "IDQ_ALL_DSB_CYCLES_6_UOPS" "IDQ_ALL_MITE_CYCLES_ANY_UOPS" "IDQ_ALL_MITE_CYCLES_1_UOPS" "IDQ_ALL_MITE_CYCLES_2_UOPS" "IDQ_ALL_MITE_CYCLES_3_UOPS" "IDQ_ALL_MITE_CYCLES_4_UOPS" "IDQ_ALL_MITE_CYCLES_5_UOPS" "IDQ_ALL_MITE_CYCLES_6_UOPS" "IDQ_ALL_CYCLES_ANY_UOPS" "IDQ_ALL_CYCLES_1_UOPS" "IDQ_ALL_CYCLES_2_UOPS" "IDQ_ALL_CYCLES_3_UOPS" "IDQ_ALL_CYCLES_4_UOPS" "IDQ_ALL_CYCLES_5_UOPS" "IDQ_ALL_CYCLES_6_UOPS" "L2_LINES_IN_I" "L2_LINES_IN_S" "L2_LINES_IN_E" "L2_LINES_IN_ALL" "L2_LINES_OUT_SILENT" "L2_LINES_OUT_NON_SILENT" "L2_LINES_OUT_USELESS_PREF" "ARITH_DIVIDER_ACTIVE" "ARITH_DIVIDER_COUNT" "LSD_UOPS" "LSD_UOPS_CYCLES_1" "LSD_UOPS_CYCLES_2" "LSD_UOPS_CYCLES_3" "LSD_UOPS_CYCLES_4" "LSD_UOPS_CYCLES_ACTIVE" "LSD_UOPS_CYCLES_INACTIVE" "OTHER_ASSISTS_ANY" "FRONTEND_RETIRED_LATENCY_GE_8" "FRONTEND_RETIRED_LATENCY_GE_16" "FRONTEND_RETIRED_LATENCY_GE_32" "FRONTEND_RETIRED_LATENCY_GE_64" "FRONTEND_RETIRED_LATENCY_GE_128" "FRONTEND_RETIRED_LATENCY_GE_256" "FRONTEND_RETIRED_LATENCY_GE_512" "FRONTEND_RETIRED_LATENCY_GE_2_BUBBLES_GE_1" "FRONTEND_RETIRED_LATENCY_GE_2_BUBBLES_GE_3" "OFFCORE_RESPONSE_0_OPTIONS" "OFFCORE_RESPONSE_1_OPTIONS")

CBOX=("CACHE_LOOKUP_M" "CACHE_LOOKUP_E" "CACHE_LOOKUP_S" "CACHE_LOOKUP_I" "CACHE_LOOKUP_READ_FILTER" "CACHE_LOOKUP_WRITE_FILTER" "CACHE_LOOKUP_EXTSNP_FILTER" "CACHE_LOOKUP_ANY_REQUEST_FILTER" "CACHE_LOOKUP_READ_M" "CACHE_LOOKUP_WRITE_M" "CACHE_LOOKUP_EXTSNP_M" "CACHE_LOOKUP_ANY_M" "CACHE_LOOKUP_READ_E" "CACHE_LOOKUP_WRITE_E" "CACHE_LOOKUP_EXTSNP_E" "CACHE_LOOKUP_ANY_E" "CACHE_LOOKUP_READ_S" "CACHE_LOOKUP_WRITE_S" "CACHE_LOOKUP_EXTSNP_S" "CACHE_LOOKUP_ANY_S" "CACHE_LOOKUP_READ_ES" "CACHE_LOOKUP_WRITE_ES" "CACHE_LOOKUP_EXTSNP_ES" "CACHE_LOOKUP_ANY_ES" "CACHE_LOOKUP_READ_I" "CACHE_LOOKUP_WRITE_I" "CACHE_LOOKUP_EXTSNP_I" "CACHE_LOOKUP_ANY_I" "CACHE_LOOKUP_READ_MESI" "CACHE_LOOKUP_WRITE_MESI" "CACHE_LOOKUP_EXTSNP_MESI" "CACHE_LOOKUP_ANY_MESI" "XSNP_RESPONSE_MISS_EXTERNAL" "XSNP_RESPONSE_MISS_XCORE" "XSNP_RESPONSE_MISS_EVICTION" "XSNP_RESPONSE_HIT_EXTERNAL" "XSNP_RESPONSE_HIT_XCORE" "XSNP_RESPONSE_HIT_EVICTION" "XSNP_RESPONSE_HITM_EXTERNAL" "XSNP_RESPONSE_HITM_XCORE" "XSNP_RESPONSE_HITM_EVICTION")


output_log="/home/hpc/Desktop/HPC/HPC_BOOST/unprocessed_data/$FILENAME.log"
output_log_temp="/home/hpc/Desktop/HPC/HPC_BOOST/unprocessed_data/$FILENAME-temp.log"
if [ -e "$output_log" ]; then
    rm "$output_log"
fi

FIXED_COUNTERS=TEMP_CORE:TMP0,PWR_PKG_ENERGY:PWR0,PWR_PP0_ENERGY:PWR1,PWR_PP1_ENERGY:PWR2,PWR_DRAM_ENERGY:PWR3,PWR_PLATFORM_ENERGY:PWR4,UNCORE_CLOCK:UBOXFIX,PP0_TEMP:MBOX0TMP0,PP1_TEMP:MBOX0TMP1,IO_REQUESTS:MBOX0C0,DRAM_READS:MBOX0C1,DRAM_WRITES:MBOX0C2,VOLTAGE_CORE:VTG0,APERF:APERF,MPERF:MPERF,PPERF:PPERF

PMC_REGISTERS=("PMC0" "PMC1" "PMC2" "PMC3")
CBOX_REGISTERS=("CBOX0C0" "CBOX0C1" "CBOX1C0" "CBOX1C1" "CBOX2C0" "CBOX2C1")

while true; do
    PMC_COUNTERS=
    UBOX0_COUNTER=
    CBOX_COUNTERS=
    UBOX1_COUNTER=
    pmc_items=("${PMC[@]:0:4}")
    if [ ${#pmc_items[@]} -gt 0 ]; then
    for i in "${!pmc_items[@]}"; do
        item="${pmc_items[i]}"
        if [ $i -lt 4 ]; then
            PMC_COUNTERS="$PMC_COUNTERS,$item:${PMC_REGISTERS[i]}"
        fi
    done
    PMC=("${PMC[@]:4}")
    fi

    PMC_COUNTERS="${PMC_COUNTERS#,}"

    cbox_items=("${CBOX[@]:0:6}")
    if [ ${#cbox_items[@]} -gt 0 ]; then
        for i in "${!cbox_items[@]}"; do
            if [ $i -lt 6 ]; then
                CBOX_COUNTERS="$CBOX_COUNTERS,$cbox_items:${CBOX_REGISTERS[i]}"
            fi
        done
        CBOX=("${CBOX[@]:6}") 
    fi
    CBOX_COUNTERS="${CBOX_COUNTERS#,}"

    if [ ${#UBOX0[@]} -gt 0 ]; then
        ubox0_item="${UBOX0[0]}"
        UBOX0_COUNTER="$ubox0_item:UBOX0"
        UBOX0=("${UBOX0[@]:1}")
    fi

    if [ ${#UBOX1[@]} -gt 0 ]; then
        ubox1_item="${UBOX1[0]}"
        UBOX1_COUNTER="$ubox1_item:UBOX1"
        UBOX1=("${UBOX1[@]:1}") 
    fi

    if [ ${#PMC[@]} -eq 0 ] && [ ${#CBOX[@]} -eq 0 ] && [ ${#UBOX0[@]} -eq 0 ] && [ ${#UBOX1[@]} -eq 0 ]; then
        break
    fi

        likwid_command="likwid-perfctr -t 10ms -C 0-3 -o ${output_log_temp} -g "

    if [ -n "$FIXED_COUNTERS" ]; then
        likwid_command+="$FIXED_COUNTERS"
    fi

    if [ -n "$PMC_COUNTERS" ]; then
        likwid_command+=",$PMC_COUNTERS"
    fi

    if [ -n "$CBOX_COUNTERS" ]; then
        likwid_command+=",$CBOX_COUNTERS"
    fi

    if [ -n "$UBOX0_COUNTER" ]; then
        likwid_command+=",$UBOX0_COUNTER"
    fi

    if [ -n "$UBOX1_COUNTER" ]; then
        likwid_command+=",$UBOX1_COUNTER"
    fi

    for arg in "$@"; do
    likwid_command="$likwid_command $arg"
    done
    echo $likwid_command
    $likwid_command
    cat "$output_log_temp" >> "$output_log"
done

echo "Performance counter data saved to $output_log"
rm "$output_log_temp"